### ISSUE TITLE
URL's get duplicated at the PreMiD presence creator

### ISSUE THREAD

**Issue by DevPjotr** [eggsy/website#10]
# Reproduce

![scr](https://i.imgur.com/s2kUk1J.png)

Add 2 domains in this format

![scr](https://i.imgur.com/ctpBsIB.png)

Remove **one**

![scr](https://i.imgur.com/ApPni34.png)
All disappeared

# Fix
Just check if the value is already in the box.

**Comment by eggsy** [comment]
This will be fixed on the next deployment. Thank you for reporting this issue. Just for your information; this page doesn't check everything (e.g. if you write https://egg, it'll think it's a valid URL since I'm using the built-in URL API which might be changed in the future), so you have to make sure to check your result even if it was created with this tool.

**Comment by eggsy** [comment]
Fixed with https://github.com/eggsy/website/commit/2e9add4ed7224ac2cc7e675c68aae439497bb9b7.
