### ISSUE TITLE
Code blocks overlaps the social buttons and overflows the entire page width

### ISSUE THREAD

**Issue by andatoshiki** [eggsy/website#53]
# Issue type: Questions and Advises
## Time created: 2023-05-03T15:35:48+08:00

- [x] Have I searched through issue?
- [x] Have tried on my own to fix?
- [ ] Possible solution found?

Great website first of all! Thanks for open sourcing this website as one of my inspiration on building on my own blog, but I found a slight bug for the site where if I call code blocks using the traditional markdown syntax; triple grave accent key, at the beginning of the blog (normally it wouldn't be required but I just went to that level for testing), the code block does not seems to have any related styles nor Vue components as I skimmed through the directory, thus a small annoying issue appears as I attaches in the following image, the code blocks overflows and overlaps the social icons on desktop view with its base color, the code blocks doesn't seem to be fitting the max width of the original blog post size, so my question is, is this is a bug or it is designed in this way? If it's a design negligence how could it be fixed since I am not so familiar with VueJS, could you possibly provide a general walk through.

> **Note**: Another small advice is to integrated math support to `@nuxt/content` since is not natively supported as a third party utilities, some of the users has given options and self-tested guide in the issue tab of the official nuxt repo, the following are some possible useful issue links.
> - https://github.com/nuxt/content/issues/102
> - https://github.com/nuxt/content/issues/133
> - https://stackoverflow.com/questions/75115043/nuxt-v3-with-nuxt-content-how-to-render-math-equations-in-markdown

![image](https://user-images.githubusercontent.com/101481353/235855884-1f4746dd-cec3-4726-877b-4a85c14be80d.png)

**Comment by eggsy** [comment]
This is actually a known issue as I added a `indicatorsHidden` prop to hide these social buttons. It’s not a fix but just a patch since I didn’t really need it anywhere else than the Spotify post. You could simply add that to the front matter part of your .md file and hide the buttons. You can also change the style of the code blocks, maybe remove the box shadow (the overflowing background color) from your CSS? 

As for the Latex support, since I don’t use it in my posts I’m not thinking of adding it as this is already a really heavy project. You can try to add it to your own fork.

**Comment by andatoshiki** [comment]
Alright, thanks for the quick reply, I'll get the styles a try, LaTeX is working properly on my fork. I'll close is this issue since it resolves my question.
